In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.0.0+cu118


### Tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# get tensor back as int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
 # Tensor
 TENSOR = torch.tensor([[[1,2,3],
                         [3,6,9],
                         [2,4,5]]])
 TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0][0]

tensor([1, 2, 3])

In [ ]:
# Create random tensor
RANDOM_TENSOR = torch.rand(3,4)
RANDOM_TENSOR

tensor([[0.4501, 0.6487, 0.4053, 0.8973],
        [0.6472, 0.1651, 0.9592, 0.2084],
        [0.5521, 0.8895, 0.2257, 0.6734]])

In [ ]:
RANDOM_TENSOR.ndim

2

In [ ]:
RANDOM_TENSOR.shape

torch.Size([3, 4])

In [ ]:
# Random tensor with similar shape to an image tensor
RANDOM_IMAGE_SIZE_TENSOR = torch.rand(size=(224, 224, 3))
RANDOM_IMAGE_SIZE_TENSOR.shape, RANDOM_IMAGE_SIZE_TENSOR.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [ ]:
# Tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Range of tensors

In [ ]:
zero_to_nine = torch.arange(start=0, end=10, step=0.99)
zero_to_nine

tensor([0.0000, 0.9900, 1.9800, 2.9700, 3.9600, 4.9500, 5.9400, 6.9300, 7.9200,
        8.9100, 9.9000])

In [ ]:
# tensors like
ten_zeroes = torch.zeros_like(zero_to_nine)
ten_zeroes

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Tensor Datatypes

In [ ]:
# Float 32 Tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

### Tensor MetaData

In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8058, 0.1954, 0.6792, 0.8534],
        [0.5455, 0.2310, 0.9549, 0.3902],
        [0.9057, 0.2136, 0.0999, 0.0841]])

In [ ]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.8058, 0.1954, 0.6792, 0.8534],
        [0.5455, 0.2310, 0.9549, 0.3902],
        [0.9057, 0.2136, 0.0999, 0.0841]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors

In [ ]:
tensor = torch.rand(100, 100)
tensor + 10

tensor([[10.3128, 10.5890, 10.8257,  ..., 10.6967, 10.8672, 10.5407],
        [10.1584, 10.0522, 10.4445,  ..., 10.1747, 10.4454, 10.4099],
        [10.1389, 10.6264, 10.0493,  ..., 10.0258, 10.2672, 10.1307],
        ...,
        [10.4917, 10.1876, 10.0989,  ..., 10.9922, 10.5853, 10.1780],
        [10.1505, 10.0175, 10.8254,  ..., 10.4712, 10.4758, 10.5142],
        [10.1967, 10.6485, 10.4712,  ..., 10.2127, 10.3316, 10.3083]])

In [ ]:
tensor * 10

tensor([[3.1277, 5.8896, 8.2571,  ..., 6.9666, 8.6721, 5.4074],
        [1.5841, 0.5217, 4.4446,  ..., 1.7474, 4.4544, 4.0986],
        [1.3886, 6.2636, 0.4935,  ..., 0.2582, 2.6724, 1.3066],
        ...,
        [4.9174, 1.8758, 0.9895,  ..., 9.9225, 5.8526, 1.7795],
        [1.5047, 0.1755, 8.2535,  ..., 4.7122, 4.7579, 5.1423],
        [1.9672, 6.4854, 4.7121,  ..., 2.1268, 3.3164, 3.0829]])

### Matrix Multiplication

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 637 µs, sys: 772 µs, total: 1.41 ms
Wall time: 16.4 ms


tensor([[25.2454, 23.1321, 21.7036,  ..., 22.6916, 25.9821, 22.2608],
        [21.9461, 22.7170, 19.4785,  ..., 19.3140, 23.0350, 21.7155],
        [21.6678, 22.9755, 20.4713,  ..., 20.8733, 22.9272, 22.0036],
        ...,
        [24.3417, 22.2766, 21.5368,  ..., 22.8432, 23.0644, 21.8920],
        [26.2481, 26.7835, 23.2377,  ..., 24.2603, 25.5900, 24.8622],
        [24.7666, 25.1274, 22.9358,  ..., 22.8380, 24.5855, 23.0012]])

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor([32.3182, 34.1247, 28.6458, 40.6641, 31.8892, 36.6768, 36.9237, 32.4468,
        35.8314, 37.4847, 32.6311, 34.6264, 32.0650, 31.4130, 34.6522, 31.6908,
        31.3493, 32.7666, 31.0563, 30.6545, 33.0666, 33.1478, 30.8384, 35.7632,
        34.8215, 33.0241, 41.7830, 35.1585, 32.1156, 30.3431, 37.6680, 32.4285,
        35.2622, 33.8571, 32.3431, 33.4672, 29.8506, 39.1433, 30.7729, 28.1758,
        35.4066, 38.9090, 36.4572, 36.6239, 33.7686, 35.9793, 31.4381, 42.4466,
        31.2036, 35.9124, 32.1117, 33.2947, 34.0654, 34.2985, 34.8731, 36.0131,
        31.4783, 30.0886, 39.6169, 29.9532, 30.1454, 33.6185, 35.1880, 38.9896,
        25.7677, 32.6376, 31.9869, 34.4715, 31.9871, 33.9032, 35.8073, 33.0544,
        38.4225, 34.2404, 38.3316, 32.8129, 32.9014, 38.8977, 33.4671, 33.2093,
        34.3379, 31.4873, 31.0409, 36.0862, 30.3161, 32.7165, 32.1245, 34.0963,
        37.8985, 30.7085, 29.1179, 31.8611, 30.0937, 36.2322, 33.1573, 36.6025,
        36.0927, 30.2803, 33.9770, 30.29

In [ ]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Tensor Aggregation

In [ ]:
x = torch.arange(0, 100, 10)
torch.min(x)

tensor(0)

In [ ]:
x.max()

tensor(90)

In [ ]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [ ]:
x.argmin(), x.argmax()

(tensor(0), tensor(9))

### Reshaping, Stacking, Squeezing, and Unsqueezing Tensors

In [ ]:
x = torch.arange(1, 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [ ]:
z = x.view(1, 9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
z[:, 0] = 5
z, x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim = 0)
x_stacked, x_stacked.shape

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
         [5, 2, 3, 4, 5, 6, 7, 8, 9],
         [5, 2, 3, 4, 5, 6, 7, 8, 9],
         [5, 2, 3, 4, 5, 6, 7, 8, 9]]),
 torch.Size([4, 9]))

In [ ]:
x_squeezed = x_reshaped.squeeze()
x_squeezed, x_squeezed.squeeze().shape

(tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
x_squeezed.unsqueeze(dim=1)

tensor([[5],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [ ]:
x_original = torch.rand(size=(224, 224, 3))
x_permuted = x_original.permute(2, 0, 1)
x_permuted.shape

torch.Size([3, 224, 224])

### Indexing

In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0, 0]

tensor([1, 2, 3])

In [ ]:
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
x[:, 1, 1]

tensor([5])

In [ ]:
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
x[:, 2, 2]

tensor([9])

In [ ]:
x[:, :, 2]

tensor([[3, 6, 9]])

### Pytorch and NumPy

In [ ]:
array = np.arange(1, 8)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1, 2, 3, 4, 5, 6, 7]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
array.dtype, tensor.dtype

(dtype('int64'), torch.float32)

In [ ]:
array = array + 1
array, tensor

(array([3, 4, 5, 6, 7, 8, 9]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
tensor = torch.ones(6)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([3., 3., 3., 3., 3., 3.]),
 array([1., 1., 1., 1., 1., 1.], dtype=float32))

### GPU

In [ ]:
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
tensor = torch.tensor([1, 2, 3], device = "cpu")

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
tensor_on_gpu.cpu().numpy()

array([1, 2, 3])